

# This file was *autogenerated* from the file utilities/ecm_with_abort.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0p5 = RealNumber('0.5'); _sage_const_10 = Integer(10); _sage_const_3 = Integer(3)
from multiprocessing import Process, Pipe 
import time


def LBound(x,a=_sage_const_1 /_sage_const_2 ,c=_sage_const_1 ):
    return exp(c*( (ln(x)**a) * (ln(ln(x))**(_sage_const_1 -a)) ))

"""
def is_L_smooth(factors, L):
    is_smooth=True
    for i in factors:
	if i>10*L:
	    is_smooth=False
	    break
    return is_smooth
"""

def fac(recv_cand, send_fac):
    while True:
	    c = recv_cand.recv()
	    c = abs(c)

	    factors = ecm.factor(c,None)
	    send_fac.send(factors)

def ecm_with_abort(n, t = _sage_const_0p5 ):
	recv_candidate,send_candidate = Pipe(duplex = False)
	recv_fac, send_fac = Pipe(duplex = False)
	proc = Process(target=fac, args=(recv_candidate, send_fac))
	proc.start()

	send_candidate.send(n)

	time.sleep(float(t))
	if recv_fac.poll():
	    factors = recv_fac.recv()
	else:
	    factors = None
	proc.terminate()
	return factors


if __name__ == "__main__":
    print(ecm_with_abort(_sage_const_2 **_sage_const_10 *_sage_const_3 **_sage_const_2 ))

